config/routes.rb
Audimax::Application.routes.draw do

  scope "(:locale)", locale: /de|en|nl/ do
  
  constraints :subdomain => /.*client$/ do
    scope :module => 'client', :as => 'client' do
      resources :inspection_objects, :as => :objects, :only => [:index, :show]
      resources :reports, :only => [:show]
      match 'contact' => 'pages#contact'
      root to: 'dashboard#index'
    end
  end

  resources :calibration_methods do
    resources :calibration_method_manuals
  end
  
  resources :calibration_method_manuals, only: [:edit, :destroy, :update]
  
  resources :client_users
  
  resources :clients do
    resources :inspection_objects
  end
    
  resources :companies do
  	member do
  		post 'destroy_image'
  	end
    resources :accreditations, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :complaints
  resources :employees do
    resources :equipment
  end
  resources :equipment do
    resources :maintenances
  end
  resources :equipment_types
  resources :inspection_objects do
    resources :participations, :only => [:new, :create]
  	resources :object_parameters, :only => [:new, :create]
  	resources :object_attachments, :only => [:new, :create]
  end
  resources :maintenance_schemes
  resources :maintenances

  get "management/report_errors"
  get "management/report_errors_per_inspector"
  get "management/complaints"
  get "management/complaints_open"
  get "management/complaints_received"
  get "management/complaints_per_type"
  get "management/complaints_per_priority"
  get "management/complaints_overdue"

  get "managers/dashboard"
  get "managers/reports"
  get "managers/report_assessments"
  get "managers/report_errors_for_each_category"

  resources :notifications, :only => [:index, :destroy] do
    member do
      put 'toggle_read'
    end
  end
  resources :object_parameters, :only => [:destroy, :edit, :update]
  resources :object_attachments, :only => [:destroy, :update]
  resources :participations, :only => [:destroy, :edit, :update]
  resources :positions
  resources :program_assessments, :only => [:edit, :update]
  resources :programs do
  	resources :regulations, :only => [:new, :create]
  	resources :scopes, :only => [:new, :create]
  end
  resources :regulations, :only => [:destroy, :edit, :show, :update] do
  	resources :sections, :only => [:new, :create, :edit, :update]
    member do
      post 'order'
    end
  end
  resources :reports do
    member do
      post 'add_equipment'
    end
  end
  resources :report_equipments, :only => [:destroy]
  resources :report_error_categories
  resources :report_errors
  resources :report_reviews
  resources :report_items, :only => [] do
    resources :report_item_attachments
  end
  resources :report_item_attachments, :only => [:destroy, :update]
  resources :scopes, :only => [:destroy, :edit, :show, :update]
  resources :sections, :only => [:destroy, :edit, :update]

  devise_for :users, controllers: {sessions: "sessions"}, :path_prefix => 'accounts', :skip => [:registrations] 
  as :user do
    get 'accounts/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts/users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  devise_scope :user do
    get 'accounts/users/verify', to: 'sessions#verify'
  end

  devise_for :client_users, :path_prefix => 'accounts', :skip => [:registrations]
  as :client_user do
    get 'accounts/client_users/edit' => 'client_user/registrations#edit', :as => 'edit_client_user_registration'
    put 'accounts/client_users' => 'client_user/registrations#update', :as => 'client_user_registration'
  end
  
  resources :users, :only => [:index, :new, :edit, :create, :update, :destroy]

  match 'about' => 'pages#about'

  root :to => 'managers#dashboard'

  
end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :birthdate, :city, :company_id, :country, :email, :employment_date, :employment_end_date, :firstname, :image, :lastname, :notes, :phone1, :phone2, :position_id, :postcode, :remove_image, :state
  
  belongs_to :position
  belongs_to :company
  has_many :equipment
  
  mount_uploader :image, ImageUploader
  
  validate :validate_employment_dates
  validates :company_id, :position_id, :presence => true
  
  def validate_employment_dates
    if !self.employment_date.nil? && !self.employment_end_date.nil? && self.employment_date > self.employment_end_date
      errors.add(:employment_date, :later_than, max: Employee.human_attribute_name('employment_end_date'))
    end
  end
  
  def fullname
  	firstname + ' ' + lastname
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  before_filter :authenticate_user!, :set_current_section
  after_filter :verify_authorized, :except => :index
  
  # GET /employees
  # GET /employees.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: EmployeesDatatable.new(view_context) }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
    authorize @employee

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new
    authorize @employee

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
    authorize @employee
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
    authorize @employee

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: I18n.t('notices.object_sucessfully_created', model: Employee.model_name.human) }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])
    authorize @employee

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to employees_path, notice: I18n.t('notices.object_sucessfully_updated', model: Employee.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    authorize @employee
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
  
  def set_current_section
    self.current_section = :assets
  end
  
end

app/views/employees/_form.html.erb
<%= form_for(@employee, :html => { :class => 'mws-form', :multipart => true }) do |f| %>
	<div class="mws-form-inline">
		<%= render partial: 'shared/errors', locals: { object: @employee } %>
		
		<div class="mws-form-row">
			<%= f.label :lastname, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :lastname, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :firstname, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :firstname, :class => 'medium' %>
			</div>
		</div>
		
		<div class="mws-form-row">
			<%= f.label :company_id, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.collection_select :company_id, Company.all, :id, :name, { :include_blank => true }, { :class => 'mws-select2 small' } %>
			</div>
		</div>
		
		<div class="mws-form-row">
			<%= f.label :position_id, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.collection_select :position_id, Position.all, :id, :name, { :include_blank => true }, { :class => 'mws-select2 small' } %>
			</div>
		</div>
		
		<div class="mws-form-row">
			<%= f.label :employment_date, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :employment_date, :class => 'mws-datepicker' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :employment_end_date, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :employment_end_date, :class => 'mws-datepicker' %>
			</div>
		</div>
		
		<div class="mws-form-row">
			<%= f.label :address, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :address, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :postcode, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :postcode, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :city, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :city, :class => 'medium' %>
			</div>
		</div>
	
		<div class="mws-form-row">
			<%= f.label :state, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :state, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :country, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.country_select :country, {include_blank: true}, { :class => 'mws-select2 small' } %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :phone1, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :phone1, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :phone2, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :phone2, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :email, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.email_field :email, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :birthdate, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :birthdate, :class => 'mws-datepicker' %>
			</div>
		</div>
		
		<% if !@employee.image_url.nil? %>
			<div class="mws-form-row">
				<div class="mws-form-item">
					<%= image_tag @employee.image_url(:thumb).to_s, :class => "img-polaroid" %><br/>
				</div>
			</div>
			<div class="mws-form-row">
				<label class="mws-form-label"><%= t('form.delete_image') %></label>
				<div class="mws-form-item">
					<%= f.check_box :remove_image, { :class => 'ibutton', 'data-label-on' => t('form.checkbox_yes'), 'data-label-off' => t('form.checkbox_no') }, "1", "0" %>
				</div>
			</div>
		<% end %>

		<div class="mws-form-row">
			<%= f.label :image, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.file_field :image %>
			</div>
		</div>
		
		<div class="mws-form-row">
			<%= f.label :notes, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_area :notes, :class => 'tinymce autosize' %>
			</div>
		</div>
		
		<div class="mws-button-row">
			<%= f.submit t('form.save'), :class => 'btn btn-danger' %>
		</div>
	</div>
<% end %>

<%= tinymce :language => I18n.locale %>

app/views/employees/edit.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= t('.edit_employee') %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-magnifier'></i> "+t('form.show')), @employee, { :class => "btn" } %>
				<%= link_to raw("<i class='icol-table'></i> "+t('form.index')), employees_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<div class="mws-panel-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/employees/index.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Employee.model_name.human(count: 2) %></span>
	</div>

	<% if policy(Employee).new? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-add'></i> "+t('form.add')), new_employee_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>

	<div class="mws-panel-body no-padding">
		<table class="mws-table mws-datatable" data-source="<%= employees_url(format: "json") %>" data-sort-column="1" data-sort-direction="asc">
			<thead>
				<tr>
					<th class="no-sort center"><%= Employee.human_attribute_name('image') %></th>
					<th><%= Employee.human_attribute_name('fullname') %></th>
					<th><%= Position.model_name.human %></th>
					<th><%= Employee.human_attribute_name('phone1') %></th>
					<th><%= Employee.human_attribute_name('email') %></th>
					<th><%= Employee.human_attribute_name('city') %></th>
					<th><%= Employee.human_attribute_name('country') %></th>
					<th class="no-sort" width="100px"></th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

app/views/employees/new.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= t('.new_employee') %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-table'></i> "+t('form.index')), employees_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<div class="mws-panel-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/employees/show.html.erb
<div class="mws-panel grid_5">
	<div class="mws-panel-header">
		<span><%= Employee.model_name.human %></span>
	</div>
	
	<% if policy(@employee).edit? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-pencil'></i> "+t('form.edit')), edit_employee_path(@employee), { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>
	
	<div class="mws-panel-body">
  		<table width="100%">
  			<td width="80%" valign="top">
				<h3><%= @employee.fullname %></h3>
				<div class="am-show-table">
					<table width="80%">
						<tbody>
							<tr><td><%= Position.model_name.human %></td><td><%= @employee.position.name unless @employee.position.nil? %></td></tr>
							<tr><td><%= Employee.human_attribute_name('address') %></td>
								<td>
									<%= @employee.address %> <br/>
									<%= @employee.postcode %> <%= @employee.city %><br/>
									<%= @employee.state %><br/>
									<%= country_name(@employee.country) %>
								</td>
							</tr>
							<tr><td><i class="icon-phone"></i></td><td><%= @employee.phone1 %></td></tr>
							<tr><td><i class="icon-mobile-phone"></i></td><td><%= @employee.phone2 %></td>
							<tr><td><i class="icon-envelope"></i></td><td><%= mail_to @employee.email %></td>
							<tr><td><%= Employee.human_attribute_name('notes') %></td><td><%= @employee.notes.html_safe unless @employee.notes.nil? %></td></tr>
						</tbody>
					</table>
				</div>				
			</td>
			<td valign="top">
				<% if !@employee.image_url.nil? %>
					<%= image_tag @employee.image_url(:thumb).to_s, :class => "img-polaroid"  %>
				<% end %>
			</td>
		</table>
	</div>
</div>

<div class="mws-panel grid_3">
	<div class="mws-panel-header">
		<span><%= t('.statistics') %></span>
	</div>
	<div class="mws-panel-body no-padding">
		<ul class="mws-summary clearfix">
			<li>
				<span class="key"><i class="icon-briefcase"></i> <%= Employee.human_attribute_name('employment_date') %></span>
				<span class="val">
					<span class="text-nowrap"><%= @employee.employment_date ? l(@employee.employment_date) : "" %></span>
				</span>
			</li>
			<li>
				<span class="key"><i class="icon-gift"></i> <%= Employee.human_attribute_name('birthdate') %></span>
				<span class="val">
					<span class="text-nowrap"><%= @employee.birthdate ? l(@employee.birthdate) : "" %></span>
				</span>
			</li>
		</ul>
	</div>
</div>

<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Equipment.model_name.human %></span>
	</div>
	
	<% if policy(Equipment).new? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-add'></i> "+t('form.add')), new_employee_equipment_path(@employee), { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>

	<div class="mws-panel-body no-padding">
		<table class="mws-table">
			<thead>
				<tr>
					<th><%= EquipmentType.human_attribute_name('image') %></th>
					<th><%= EquipmentType.human_attribute_name('name') %></th>
					<th><%= EquipmentType.human_attribute_name('model') %></th>
					<th><%= Equipment.human_attribute_name('nr') %></th>
					<th><%= Equipment.human_attribute_name('serial_nr') %></th>
					<th><%= Equipment.human_attribute_name('usage') %></th>
					<th width="100px"></th>
				</tr>
			</thead>
			<tbody>
			<% @employee.equipment.each do |equipment| %>
				<tr>
					<td align="center"><% if !equipment.equipment_type.image_url.nil? %><%= link_to image_tag(equipment.equipment_type.image_url(:thumb).to_s, :class => 'img-polaroid', :size => "100x60"), equipment.equipment_type %><%end %></td>
					<td><%= equipment.equipment_type.name %></td>
					<td><%= equipment.equipment_type.model %></td>
					<td><%= equipment.nr %></td>
					<td><%= equipment.serial_nr %></td>
					<td><%= equipment_usage_label(equipment.usage) %></td>
					<td width="100px">
						<span class="btn-group">
							<%= link_to raw("<i class='icon-search'></i>"), equipment, { :class => 'btn btn-small' } %>
							<% if policy(equipment).edit? %>
							<%= link_to raw("<i class='icon-pencil'></i>"), edit_equipment_path(equipment), { :class => 'btn btn-small' } %>
							<% end %>
							<% if policy(equipment).destroy? %>
							<%= link_to raw("<i class='icon-trash'></i>"), equipment, method: :delete, data: { confirm: 'form.confirm_delete' }, :class => 'btn btn-small'  %>
							<% end %>
						</span>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>