config/routes.rb
Audimax::Application.routes.draw do

  scope "(:locale)", locale: /de|en|nl/ do
  
  constraints :subdomain => /.*client$/ do
    scope :module => 'client', :as => 'client' do
      resources :inspection_objects, :as => :objects, :only => [:index, :show]
      resources :reports, :only => [:show]
      match 'contact' => 'pages#contact'
      root to: 'dashboard#index'
    end
  end

  resources :calibration_methods do
    resources :calibration_method_manuals
  end
  
  resources :calibration_method_manuals, only: [:edit, :destroy, :update]
  
  resources :client_users
  
  resources :clients do
    resources :inspection_objects
  end
    
  resources :companies do
  	member do
  		post 'destroy_image'
  	end
    resources :accreditations, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :complaints
  resources :employees do
    resources :equipment
  end
  resources :equipment do
    resources :maintenances
  end
  resources :equipment_types
  resources :inspection_objects do
    resources :participations, :only => [:new, :create]
  	resources :object_parameters, :only => [:new, :create]
  	resources :object_attachments, :only => [:new, :create]
  end
  resources :maintenance_schemes
  resources :maintenances

  get "management/report_errors"
  get "management/report_errors_per_inspector"
  get "management/complaints"
  get "management/complaints_open"
  get "management/complaints_received"
  get "management/complaints_per_type"
  get "management/complaints_per_priority"
  get "management/complaints_overdue"

  get "managers/dashboard"
  get "managers/reports"
  get "managers/report_assessments"
  get "managers/report_errors_for_each_category"

  resources :notifications, :only => [:index, :destroy] do
    member do
      put 'toggle_read'
    end
  end
  resources :object_parameters, :only => [:destroy, :edit, :update]
  resources :object_attachments, :only => [:destroy, :update]
  resources :participations, :only => [:destroy, :edit, :update]
  resources :positions
  resources :program_assessments, :only => [:edit, :update]
  resources :programs do
  	resources :regulations, :only => [:new, :create]
  	resources :scopes, :only => [:new, :create]
  end
  resources :regulations, :only => [:destroy, :edit, :show, :update] do
  	resources :sections, :only => [:new, :create, :edit, :update]
    member do
      post 'order'
    end
  end
  resources :reports do
    member do
      post 'add_equipment'
    end
  end
  resources :report_equipments, :only => [:destroy]
  resources :report_error_categories
  resources :report_errors
  resources :report_reviews
  resources :report_items, :only => [] do
    resources :report_item_attachments
  end
  resources :report_item_attachments, :only => [:destroy, :update]
  resources :scopes, :only => [:destroy, :edit, :show, :update]
  resources :sections, :only => [:destroy, :edit, :update]

  devise_for :users, controllers: {sessions: "sessions"}, :path_prefix => 'accounts', :skip => [:registrations] 
  as :user do
    get 'accounts/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts/users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  devise_scope :user do
    get 'accounts/users/verify', to: 'sessions#verify'
  end

  devise_for :client_users, :path_prefix => 'accounts', :skip => [:registrations]
  as :client_user do
    get 'accounts/client_users/edit' => 'client_user/registrations#edit', :as => 'edit_client_user_registration'
    put 'accounts/client_users' => 'client_user/registrations#update', :as => 'client_user_registration'
  end
  
  resources :users, :only => [:index, :new, :edit, :create, :update, :destroy]

  match 'about' => 'pages#about'

  root :to => 'managers#dashboard'

  
end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  
  before_filter :authenticate_user!, :set_current_section
  
  def report_errors
    @errors_per_category_chart = ReportErrorsPerCategoryChart.new
    respond_to do |format|
      format.html
      format.json { render json: ReportErrorsChart.new }
    end
  end
  
  def report_errors_per_inspector
    respond_to do |format|
      format.json { render json: ReportErrorsPerInspectorChart.new(params[:category_id]) }
      #format.json { render json: ReportErrorsPerInspectorChart.new(9) }
    end
  end
  
  def complaints
    @complaints_overdue_chart = ComplaintsOverdueChart.new
    @complaints_dashboard = ComplaintsDashboard.new
    
    respond_to do |format|
      format.html
    end
  end
  
  # chart
  def complaints_open
    respond_to do |format|
      format.json { render json: ComplaintsOpenChart.new}
    end
  end
  
  # chart
  def complaints_received
    respond_to do |format|
      format.json { render json: ComplaintsReceivedChart.new}
    end
  end
  
  # chart
  def complaints_per_type
    respond_to do |format|
      format.json { render json: ComplaintsPerTypeChart.new}
    end
  end
  
  # chart
  def complaints_per_priority
    respond_to do |format|
      format.json { render json: ComplaintsPerPriorityChart.new}
    end
  end
  
  #chart
  def complaints_overdue
    respond_to do |format|
      format.json { render json: ComplaintsOverdueChart.new}
    end
  end
  
  def set_current_section
    self.current_section = :management
  end 

end

app/views/management/complaints.html.erb
<div class="mws-panel grid_6">
	<div class="mws-panel-header">
    	<span><i class="icon-graph"></i> <%= t('.complaints_received') %></span>
    </div>
    <div class="mws-panel-body">
		<div id="chart-complaints-received" class="am-chart" style="height: 222px;" data-source="<%= management_complaints_received_url(format: "json") %>"></div>
    </div>
</div>

<div class="mws-panel grid_2">
	<div class="mws-panel-header">
    	<span><i class="icon-chart"></i> <%= t('.complaints_overdue') %></span>
    </div>
    <div class="mws-panel-body">
    	<div class="mws-panel-content">
    		<div id="chart-complaints-overdue" style="width:100%; height:222px; "></div>
    	</div>
    </div>
</div>

<div class="mws-panel grid_3">
	<div class="mws-panel-header">
    	<span><i class="icon-stats"></i> <%= t('.statistics')%></span>
    </div>
    <div class="mws-panel-body no-padding">
		<ul class="mws-summary clearfix">
			<li>
				<span class="key" style="width: 200px"><i class="icon-lightning-3"></i> <%= t('.nr_open_complaints') %></span>
				<span class="val">
					<span class="text-nowrap"><%= @complaints_dashboard.nr_open_complaints %></span>
				</span>
			</li>
			<li>
				<span class="key" style="width: 200px"><i class="icon-calendar"></i> <%= t('.days_since_last_complaint') %></span>
				<span class="val">
					<span class="text-nowrap"><%= @complaints_dashboard.days_since_last_complaint %></span>
				</span>
			</li>
			<li>
				<span class="key" style="width: 200px"><i class="icon-lightning-2"></i> <%= t('.nr_complaints')%></span>
				<span class="val">
					<span class="text-nowrap"><%= @complaints_dashboard.nr_complaints %></span>
				</span>
			</li>
			<li>
				<span class="key" style="width: 200px"><i class="icon-gauge"></i> <%= t('.average_handling_days') %></span>
				<span class="val">
					<span class="text-nowrap"><%= @complaints_dashboard.average_handling_days %> dagen</span>
				</span>
			</li>
			<li>
				<span class="key" style="width: 200px"></span>
				<span class="val">
					<span class="text-nowrap"></span>
				</span>
			</li>
			<li>
				<span class="key" style="width: 200px"></span>
				<span class="val">
					<span class="text-nowrap"></span>
				</span>
			</li>
		</ul>
    </div>
</div>

<div class="mws-panel grid_2">
	<div class="mws-panel-header">
    	<span><i class="icon-chart"></i> <%= t('.complaints_per_type') %></span>
    </div>
    <div class="mws-panel-body">
    	<div class="mws-panel-content">
    		<div id="chart-complaints-per-type" style="width:100%; height:222px; " class="am-chart" data-source="<%= management_complaints_per_type_url(format: "json") %>"></div>
    	</div>
    </div>
</div>

<div class="mws-panel grid_3">
	<div class="mws-panel-header">
    	<span><i class="icon-bars"></i> <%= t('.complaints_per_priority') %></span>
    </div>
    <div class="mws-panel-body">
    	<div class="mws-panel-content">
    		<div id="chart-complaints-per-priority" class="am-chart" style="width:100%; height:222px" data-source="<%= management_complaints_per_priority_url(format: "json") %>"></div>
    	</div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		if ($.plot) {

			var data = [
			<% @complaints_overdue_chart.series_data.each do |cat| %>
				{label: '<%= cat[:label] %>', data: <%= cat[:data] %>, color: '<%= cat[:color] %>' },
			<% end %>
			];
			
			function labelFormatter(label, series) {
				return "<div style='font-size:8pt; text-align:center; padding:2px; color:black;'>" + series.percent.toFixed(0) + "%</div>"
			}
			
			$.plot($("#chart-complaints-overdue"),
				data, {
				series: {
					pie: {
						show: true,
						label: { 
							show: true,
							radius: 0.90,
							formatter: labelFormatter
						}
					}
				},
				legend: {
					show: true,
				},
	            grid: {
	                hoverable: true
	            }
			});
		}
	});
</script>

app/views/management/report_errors.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
    	<span><i class="icon-graph"></i> <%= t('.average_errors_per_report') %></span>
    </div>
    <div class="mws-panel-body">
        <div id="chart-avg-errors" class="am-chart" style="height: 222px;" data-source="<%= management_report_errors_url(format: "json") %>"></div>
    </div>
</div>

<div class="mws-panel grid_4">
	<div class="mws-panel-header">
    	<span><i class="icon-chart"></i> <%= t('.errors_per_category') %></span>
    </div>
    <div class="mws-panel-body">
    	<div class="mws-panel-content">
			<div id="chart-errors-per-category" style="height:300px; width:100%;"></div>
    	</div>
    </div>
</div>

<div class="mws-panel grid_4">
	<div class="mws-panel-header">
    	<span><i class="icon-bars"></i> <%= t('.errors_per_inspector') %></span>
    </div>
    <div class="mws-panel-body">
    	<div class="mws-panel-content">
    		<div id="chart-errors-per-inspector" class="am-chart" style="width:100%; height:288px" data-source="<%= management_report_errors_per_inspector_url(format: "json") %>"></div>
			<div id="chart-errors-per-inspector-label" style="width: 100%; height: 12px; text-align: center">
    	</div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		if ($.plot) {

			var data = [
			<% @errors_per_category_chart.series_data.each do |cat| %>
				{label: '<%= cat[:label] %>', data: <%= cat[:data] %> },
			<% end %>
			];
			
			var categories = <%= @errors_per_category_chart.categories %>;

			function labelFormatter(label, series) {
				return "<div style='font-size:8pt; text-align:center; padding:2px; color:black;'>" + series.percent.toFixed(0) + "%</div>"
			}
			
			$.plot($("#chart-errors-per-category"),
				data, {
				series: {
					pie: {
						show: true,
						label: { 
							show: true,
							radius: 0.85,
							formatter: labelFormatter
						}
					}
				},
				legend: {
					show: true,
				},
	            grid: {
	                hoverable: true,
					clickable: true
	            }
			});
			
			$("#chart-errors-per-category").bind("plotclick", function (event, pos, item) {
				if (item) {
					$.ajax({
						url: 'report_errors_per_inspector.json?category_id='+categories[item.seriesIndex],
						type: "GET",
						dataType: "json",
						success: function(chart) { $("#chart-errors-per-inspector-label").text(item.series.label); chart.data[0].color = item.series.color; $.plot($("#chart-errors-per-inspector"), chart.data, chart.options); }
					});
				} else {
					$.ajax({
						url: 'report_errors_per_inspector.json',
						type: "GET",
						dataType: "json",
						success: function(chart) { $("#chart-errors-per-inspector-label").text(""); $.plot($("#chart-errors-per-inspector"), chart.data, chart.options); }
					});
				}
			});		
			
		}
	});
</script>