config/routes.rb
Audimax::Application.routes.draw do

  scope "(:locale)", locale: /de|en|nl/ do
  
  constraints :subdomain => /.*client$/ do
    scope :module => 'client', :as => 'client' do
      resources :inspection_objects, :as => :objects, :only => [:index, :show]
      resources :reports, :only => [:show]
      match 'contact' => 'pages#contact'
      root to: 'dashboard#index'
    end
  end

  resources :calibration_methods do
    resources :calibration_method_manuals
  end
  
  resources :calibration_method_manuals, only: [:edit, :destroy, :update]
  
  resources :client_users
  
  resources :clients do
    resources :inspection_objects
  end
    
  resources :companies do
  	member do
  		post 'destroy_image'
  	end
    resources :accreditations, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :complaints
  resources :employees do
    resources :equipment
  end
  resources :equipment do
    resources :maintenances
  end
  resources :equipment_types
  resources :inspection_objects do
    resources :participations, :only => [:new, :create]
  	resources :object_parameters, :only => [:new, :create]
  	resources :object_attachments, :only => [:new, :create]
  end
  resources :maintenance_schemes
  resources :maintenances

  get "management/report_errors"
  get "management/report_errors_per_inspector"
  get "management/complaints"
  get "management/complaints_open"
  get "management/complaints_received"
  get "management/complaints_per_type"
  get "management/complaints_per_priority"
  get "management/complaints_overdue"

  get "managers/dashboard"
  get "managers/reports"
  get "managers/report_assessments"
  get "managers/report_errors_for_each_category"

  resources :notifications, :only => [:index, :destroy] do
    member do
      put 'toggle_read'
    end
  end
  resources :object_parameters, :only => [:destroy, :edit, :update]
  resources :object_attachments, :only => [:destroy, :update]
  resources :participations, :only => [:destroy, :edit, :update]
  resources :positions
  resources :program_assessments, :only => [:edit, :update]
  resources :programs do
  	resources :regulations, :only => [:new, :create]
  	resources :scopes, :only => [:new, :create]
  end
  resources :regulations, :only => [:destroy, :edit, :show, :update] do
  	resources :sections, :only => [:new, :create, :edit, :update]
    member do
      post 'order'
    end
  end
  resources :reports do
    member do
      post 'add_equipment'
    end
  end
  resources :report_equipments, :only => [:destroy]
  resources :report_error_categories
  resources :report_errors
  resources :report_reviews
  resources :report_items, :only => [] do
    resources :report_item_attachments
  end
  resources :report_item_attachments, :only => [:destroy, :update]
  resources :scopes, :only => [:destroy, :edit, :show, :update]
  resources :sections, :only => [:destroy, :edit, :update]

  devise_for :users, controllers: {sessions: "sessions"}, :path_prefix => 'accounts', :skip => [:registrations] 
  as :user do
    get 'accounts/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts/users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  devise_scope :user do
    get 'accounts/users/verify', to: 'sessions#verify'
  end

  devise_for :client_users, :path_prefix => 'accounts', :skip => [:registrations]
  as :client_user do
    get 'accounts/client_users/edit' => 'client_user/registrations#edit', :as => 'edit_client_user_registration'
    put 'accounts/client_users' => 'client_user/registrations#update', :as => 'client_user_registration'
  end
  
  resources :users, :only => [:index, :new, :edit, :create, :update, :destroy]

  match 'about' => 'pages#about'

  root :to => 'managers#dashboard'

  
end
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :city, :name, :postalcode, :state, :country, :phone, :fax, :email, :web, :image, :remove_image
  
  has_many :accreditations
  
  validates :name, :presence => true
  
  mount_uploader :image, ImageUploader
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :authenticate_user!, :set_current_section
  after_filter :verify_authorized, :except => :index
  
  # GET /companies
  # GET /companies.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: CompaniesDatatable.new(view_context) }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    authorize @company

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    authorize @company

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    authorize @company
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])
    authorize @company

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_path, notice:  I18n.t('notices.object_sucessfully_created', model: Company.model_name.human) }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])
    authorize @company

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to companies_path, notice: I18n.t('notices.object_sucessfully_updated', model: Company.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /companies/1/destroy_image
	def destroy_image
    @company = Company.find(params[:id])
    authorize @company

		@company.remove_image = true
		@company.save
    respond_to do |format|
      # format.html { redirect_to companies_url }
      format.js
    end		
	end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    authorize @company
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
  
  def set_current_section
    self.current_section = :company
  end
	
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => { :class => 'mws-form', :multipart => true }) do |f| %>
	<div class="mws-form-inline">
		<%= render partial: 'shared/errors', locals: { object: @company } %>
		
		<div class="mws-form-row">
			<%= f.label :name, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :name, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :address, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :address, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :postalcode, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :postalcode, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :city, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :city, :class => 'medium' %>
			</div>
		</div>
	
		<div class="mws-form-row">
			<%= f.label :state, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.text_field :state, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :country, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.country_select :country, {include_blank: true}, { :class => 'mws-select2 medium' } %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :phone, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.phone_field :phone, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :fax, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.phone_field :fax, :class => 'medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :email, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.email_field :email, :class => 'email medium' %>
			</div>
		</div>

		<div class="mws-form-row">
			<%= f.label :web, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.url_field :web, :class => 'url medium' %>
			</div>
		</div>

		<% if !@company.image_url.nil? %>
			<div class="mws-form-row">
				<div class="mws-form-item">
					<div id="company_logo">
					<%= image_tag @company.image_url(:thumb).to_s, :class => "img-polaroid"  %><br/>
					</div>
				</div>
			</div>
			<div class="mws-form-row">
				<label class="mws-form-label"><%= t('.delete_logo') %></label>
				<div class="mws-form-item">
					<%= f.check_box :remove_image, { :class => 'ibutton', 'data-label-on' => t('form.checkbox_yes'), 'data-label-off' => t('form.checkbox_no') }, "1", "0" %>
				</div>
			</div>
		<% end %>
		
		<div class="mws-form-row">
			<%= f.label :image, :class => 'mws-form-label' %>
			<div class="mws-form-item">
				<%= f.file_field :image %>
			</div>
		</div>
			
		<div class="mws-button-row">
			<%= f.submit t('form.save'), :class => 'btn btn-danger' %>
		</div>
	</div>
<% end %>

app/views/companies/destroy_image.js.erb
$('#company_logo').fadeOut()

app/views/companies/edit.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= t('.edit_company') %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-magnifier'></i> "+t('form.show')), @company, { :class => "btn" } %>
				<%= link_to raw("<i class='icol-table'></i> "+t('form.index')), companies_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<div class="mws-panel-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/companies/index.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Company.model_name.human(count: 2) %></span>
	</div>
	
	<% if policy(Company).new? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-add'></i> "+t('form.add')), new_company_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>
	
	<div class="mws-panel-body no-padding">
		<table class="mws-table mws-datatable" data-source="<%= companies_url(format: "json") %>" data-sort-column="1" data-sort-direction="asc">
			<thead>
				<tr>
					<th class="no-sort center"><% t('.logo') %></th>
					<th><%= Company.human_attribute_name('name') %></th>
					<th><%= Company.human_attribute_name('address') %></th>
					<th><%= Company.human_attribute_name('postcode') %></th>
					<th><%= Company.human_attribute_name('city') %></th>
					<th><%= Company.human_attribute_name('state') %></th>
					<th><%= Company.human_attribute_name('country') %></th>
					<th class="no-sort" width="100px"></th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>

</div>

app/views/companies/new.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= t('.new_company') %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-table'></i> "+t('form.index')), companies_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<div class="mws-panel-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/companies/show.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= Company.model_name.human %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<% if policy(@company).edit? %>
				<%= link_to raw("<i class='icol-pencil'></i> "+t('form.edit')), edit_company_path(@company), { :class => "btn" } %>
				<% end %>
				<%= link_to raw("<i class='icol-table'></i> "+t('form.index')), companies_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<div class="mws-panel-body">
		<table width="100%">
			<tr>
				<td width="80%" valign="top">
					<h3><%= @company.name %></h3>
					<div class="am-show-table">
						<table width="80%">
							<tbody>
								<tr><td><%= Company.human_attribute_name('address') %></td>
									<td>
										<%= @company.address %> <br/>
										<%= @company.postalcode %> <%= @company.city %><br/>
										<%= @company.state %><br/>
										<%= country_name(@company.country) %>
									</td>
								</tr>
								<tr><td><i class="icon-phone"></i></td><td><%= @company.phone %></td></tr>
								<tr><td><i class="icon-print"></i></td><td><%= @company.fax %></td>
								<tr><td><i class="icon-envelope"></i></td><td><%= mail_to @company.email %></td>
								<tr><td><i class="icon-safari"></i></td><td><%= link_to @company.web, @company.web, :target => '_blank'  %></td>
							</tbody>
						</table>
					</div>						
				</td>
				<td valign="top">
					<% if !@company.image_url.nil? %>
						<%= image_tag @company.image_url(:thumb).to_s, :class => "img-polaroid"  %>
					<% end %>
				</td>
			</tr>
		</table>
	</div>
</div>

<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Accreditation.model_name.human(count: 2) %></span>
	</div>
	
	<% if policy(Accreditation).new? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-add'></i> "+t('form.add')), new_company_accreditation_path(@company), { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>

	<div class="mws-panel-body no-padding">
		<table class="mws-table">
			<thead>
				<tr>
					<th><%= Program.model_name.human %></th>
					<th><%= Scope.model_name.human %></th>
					<th><%= Accreditation.human_attribute_name('start_date') %></th>
					<th><%= Accreditation.human_attribute_name('end_date') %></th>
					<th><%= Program.human_attribute_name('logo') %></th>
					<th width="100px"></th>
				</tr>
			</thead>
			<tbody>
			<% @company.accreditations.each do |accreditation| %>
				<tr>
					<td><%= accreditation.scope.program.name %></td>
					<td><%= accreditation.scope.name %></td>
					<td><%= accreditation.start_date %></td>
					<td><%= accreditation.end_date %></td>
					<td align="center"><% if !accreditation.image_url.nil? %><%= image_tag(accreditation.image_url(:thumb).to_s, :class => 'img-polaroid', :size => "80x48") %><%end %></td>
					<td width="100px">
						<span class="btn-group">
							<% if policy(accreditation).edit? %>
							<%= link_to raw("<i class='icon-pencil'></i>"), edit_company_accreditation_path(@company, accreditation), { :class => 'btn btn-small' } %>
							<% end %>
							<% if policy(accreditation).destroy? %>
							<%= link_to raw("<i class='icon-trash'></i>"), company_accreditation_path(@company, accreditation), method: :delete, data: { confirm: t('form.confirm_delete') }, :class => 'btn btn-small'  %>
							<% end %>
						</span>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>