config/routes.rb
Audimax::Application.routes.draw do

  scope "(:locale)", locale: /de|en|nl/ do
  
  constraints :subdomain => /.*client$/ do
    scope :module => 'client', :as => 'client' do
      resources :inspection_objects, :as => :objects, :only => [:index, :show]
      resources :reports, :only => [:show]
      match 'contact' => 'pages#contact'
      root to: 'dashboard#index'
    end
  end

  resources :calibration_methods do
    resources :calibration_method_manuals
  end
  
  resources :calibration_method_manuals, only: [:edit, :destroy, :update]
  
  resources :client_users
  
  resources :clients do
    resources :inspection_objects
  end
    
  resources :companies do
  	member do
  		post 'destroy_image'
  	end
    resources :accreditations, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :complaints
  resources :employees do
    resources :equipment
  end
  resources :equipment do
    resources :maintenances
  end
  resources :equipment_types
  resources :inspection_objects do
    resources :participations, :only => [:new, :create]
  	resources :object_parameters, :only => [:new, :create]
  	resources :object_attachments, :only => [:new, :create]
  end
  resources :maintenance_schemes
  resources :maintenances

  get "management/report_errors"
  get "management/report_errors_per_inspector"
  get "management/complaints"
  get "management/complaints_open"
  get "management/complaints_received"
  get "management/complaints_per_type"
  get "management/complaints_per_priority"
  get "management/complaints_overdue"

  get "managers/dashboard"
  get "managers/reports"
  get "managers/report_assessments"
  get "managers/report_errors_for_each_category"

  resources :notifications, :only => [:index, :destroy] do
    member do
      put 'toggle_read'
    end
  end
  resources :object_parameters, :only => [:destroy, :edit, :update]
  resources :object_attachments, :only => [:destroy, :update]
  resources :participations, :only => [:destroy, :edit, :update]
  resources :positions
  resources :program_assessments, :only => [:edit, :update]
  resources :programs do
  	resources :regulations, :only => [:new, :create]
  	resources :scopes, :only => [:new, :create]
  end
  resources :regulations, :only => [:destroy, :edit, :show, :update] do
  	resources :sections, :only => [:new, :create, :edit, :update]
    member do
      post 'order'
    end
  end
  resources :reports do
    member do
      post 'add_equipment'
    end
  end
  resources :report_equipments, :only => [:destroy]
  resources :report_error_categories
  resources :report_errors
  resources :report_reviews
  resources :report_items, :only => [] do
    resources :report_item_attachments
  end
  resources :report_item_attachments, :only => [:destroy, :update]
  resources :scopes, :only => [:destroy, :edit, :show, :update]
  resources :sections, :only => [:destroy, :edit, :update]

  devise_for :users, controllers: {sessions: "sessions"}, :path_prefix => 'accounts', :skip => [:registrations] 
  as :user do
    get 'accounts/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts/users' => 'devise/registrations#update', :as => 'user_registration'
  end
  
  devise_scope :user do
    get 'accounts/users/verify', to: 'sessions#verify'
  end

  devise_for :client_users, :path_prefix => 'accounts', :skip => [:registrations]
  as :client_user do
    get 'accounts/client_users/edit' => 'client_user/registrations#edit', :as => 'edit_client_user_registration'
    put 'accounts/client_users' => 'client_user/registrations#update', :as => 'client_user_registration'
  end
  
  resources :users, :only => [:index, :new, :edit, :create, :update, :destroy]

  match 'about' => 'pages#about'

  root :to => 'managers#dashboard'

  
end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :comments, :employee_id, :inspection_date, :inspection_object_nr, :inspection_object_id, :report_items_attributes, :scope_id, :status
  
  belongs_to :inspection_object
  belongs_to :employee
  belongs_to :scope
  belongs_to :regulation
  has_many :report_items, :dependent => :destroy
  
  has_many :report_equipments, :dependent => :destroy
  has_many :equipment, :through => :report_equipments

  accepts_nested_attributes_for :report_items

  validates :employee_id, :inspection_object_id, :scope_id, :inspection_date, :presence => true
  
  def self.report_status_values
    [ 'NEW', 'FILED', 'REVIEW', 'FINAL']
  end
  
  def self.report_status_description(status)
    Report.human_attribute_name("status.#{status.downcase}")
  end
  
  def self.report_valid_status_transitions(status)
    { 'NEW' => ['NEW', 'FILED'],
      'FILED' => ['FILED', 'REVIEW', 'FINAL'], 
      'REVIEW' => ['FILED', 'REVIEW', 'FINAL'],
      'FINAL' => ['FINAL']
      }[status]
  end
  
  def self.create_report(object_nr, employee_id, inspection_date, scope_id)
    new_report = Report.new(:inspection_object_nr => object_nr, :employee_id => employee_id, :inspection_date => inspection_date, :scope_id => scope_id)
    
    if new_report.valid?
      new_report.status = 'NEW'
      new_report.regulation = new_report.scope.program.regulations.valid_on(new_report.inspection_date).first

      # Create report items from regulation
      if !new_report.regulation.nil?
        new_report.regulation.sections.for_scope(scope_id).each do |section|
          new_report.report_items.build(:section_id => section.id, :assessment => 'NONE')
        end
      end
    
      # Create report equipment from employee equipment
      new_report.employee.equipment.where(:usage => 'OPERATIONAL').each do |equipment|
        new_report.report_equipments.build(:equipment_id => equipment.id)
      end
    end

    new_report
  end
  
  #
  # Report status
  #
  # NEW     - A new report. Not yet filed, changes are still possible.
  # FILED   - Report is filed. Changes are nog longer possible. Report is ready for review.
  # REVIEW  - Report is being reviewed.
  # READY   - Report is ready. Review is done. Review is approved and changes in report have been applied. This is the final status.
  #
  
  #
  # Virtual attribute inspection_object_nr
  #
  
  def inspection_object_nr
  	inspection_object.nr if inspection_object
  end
  
  def inspection_object_nr=(nr)
  	self.inspection_object = InspectionObject.find_by_nr(nr) unless nr.blank?
  end
  
  def accreditation_logo
    accreditation = self.employee.company.accreditations.where("accreditations.scope_id = :scope_id and (:date >= accreditations.start_date and (:date <= accreditations.end_date or accreditations.end_date is null))", :scope_id => self.scope_id, :date => self.inspection_date).first
    accreditation.nil? ? "" : accreditation.image_url.to_s
  end

end

app/controllers/client/reports_controller.rb
class Client::ReportsController < ApplicationController
  layout 'client'
  
  before_filter :authenticate_client_user!
  after_filter :verify_authorized
  
  def show
    @report = policy_scope(Report).find(params[:id])
    authorize @report
    
    @report_items = @report.report_items.joins(:section).order("seq_nr").includes(:section)
    @assessment_names = Hash[ProgramAssessment.joins(:assessment).includes(:assessment).where("program_id = :program_id", :program_id => @report.scope.program_id).map { |a| [a.code, ((a.name.nil? or a.name.empty?) ? a.assessment.name : a.name)] }]
    @assessment_options = @assessment_names.map { |a| [a[1], a[0]] }

    @assessment_selection = I18n.t('reports.show.all_assessments')
    if params[:assessment].present?
      @assessment_selection = @assessment_names[params[:assessment]]
      @report_items = @report_items.where("report_items.assessment = :assessment", :assessment => params[:assessment])
    end

    @qr = RQRCode::QRCode.new("#{request.protocol}#{request.host_with_port}#{report_path(@report)}", :size => 6, :level => :h )
    
    @object_path = client_object_path(@report.inspection_object)

    respond_to do |format|
      format.html { render 'reports/show'}
      format.pdf  { render :template => 'reports/show', :pdf => "report#{@report.id}", :layout => "generic", :page_size => "A4", :disposition => :inline, :footer => { :left => "Inspectierapport #{@report.id}", :right => '[page]/[topage]', :font_size => 8 }, :show_as_html => params[:debug] }
    end
  end
  
  def pundit_user
    current_client_user
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :authenticate_user!, :set_current_section
  after_filter :verify_authorized, :except => :index

  # GET /reports
  # GET /reports.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: ReportsDatatable.new(view_context) }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = policy_scope(Report).find(params[:id])
    authorize @report
    
    @report_items = @report.report_items.joins(:section).order("seq_nr").includes(:section)
    @assessment_names = Hash[ProgramAssessment.joins(:assessment).includes(:assessment).where("program_id = :program_id", :program_id => @report.scope.program_id).map { |a| [a.code, ((a.name.nil? or a.name.empty?) ? a.assessment.name : a.name)] }]
    @assessment_options = @assessment_names.map { |a| [a[1], a[0]] }

    @assessment_selection = I18n.t('reports.show.all_assessments')
    if params[:assessment].present?
      @assessment_selection = @assessment_names[params[:assessment]]
      @report_items = @report_items.where("report_items.assessment = :assessment", :assessment => params[:assessment])
    end
    
    @qr = RQRCode::QRCode.new("#{request.protocol}#{request.host_with_port}#{report_path(@report)}", :size => 6, :level => :h )
    
    @object_path = inspection_object_path(@report.inspection_object)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
      format.pdf  { render :pdf => "report#{@report.id}", :layout => "generic", :page_size => "A4", :disposition => :inline, :footer => { :left => "#{Report.model_name.human} #{@report.id}", :right => '[page]/[topage]', :font_size => 8 }, :show_as_html => params[:debug] }
    end
  end

  # GET /reports/new
  def new
    @report = Report.new(:employee_id => current_user.employee_id, :inspection_date => Date.today)
    authorize @report
  end

  # GET /reports/1/edit
  def edit
    @report = policy_scope(Report).find(params[:id])
    authorize @report

    @assessment_names = Hash[ProgramAssessment.joins(:assessment).includes(:assessment).where("program_id = :program_id", :program_id => @report.scope.program_id).map { |a| [a.code, ((a.name.nil? or a.name.empty?) ? a.assessment.name : a.name)] }]
    @assessment_options = @assessment_names.map { |a| [a[1], a[0]] }
  end

  # POST /reports
  def create
    @report = Report.create_report(params[:report][:inspection_object_nr], params[:report][:employee_id], params[:report][:inspection_date], params[:report][:scope_id])
    authorize @report

    respond_to do |format|
      if @report.save
        format.html { redirect_to edit_report_path(@report) }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = policy_scope(Report).find(params[:id])
    authorize @report

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: I18n.t('notices.object_sucessfully_updated', model: Report.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = policy_scope(Report).find(params[:id])
    authorize @report
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
  
  # POST /reports/1/add_equipment?equipment_id=2
  def add_equipment
    @report = policy_scope(Report).find(params[:id])
    authorize @report, :update?
    @report.report_equipments.build(:equipment_id => params[:equipment_id])
    respond_to do |format|
      if @report.save
        format.html { redirect_to edit_report_path(@report) }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  private
  
  def set_current_section
    self.current_section = :inspection
  end  
  
end

app/helpers/reports_helper.rb
module ReportsHelper
  
  def report_status_select_options(status)
    Report.report_valid_status_transitions(status).map { |v| [ Report.report_status_description(v), v ] }
  end

	def report_status_label(status)
    label_class = {'NEW' => 'default', 'FILED' => 'important', 'REVIEW' => 'warning', 'FINAL' => 'success'}[status]
		raw("<span class='label label-#{label_class}'>#{Report.report_status_description(status)}</span>")
	end
	
	def report_assessment_class(assessment)
		{ 'COM' => 'btn-success', 'NC1' => 'btn-danger', 'NC2' => 'btn-warning', 'NA' => 'btn-inverse', 'NONE' => '', '' => '' }[assessment]
	end
	
  def report_assessment_cell_class(assessment)
		{ 'COM' => 'am-assessment-cell-success', 'NC1' => 'am-assessment-cell-error', 'NC2' => 'am-assessment-cell-warning', 'NA' => '', 'NONE' => 'am-assessment-cell-none' }[assessment]
  end

  def report_assessment_chart_color(assessment)
		{ 'COM' => '#5bb75b', 'NC1' => '#da4f49', 'NC2' => '#f89406', 'NA' => '#363636', 'NONE' => '#F4F447' }[assessment]
  end
  
end

app/views/reports/_form.html.erb
<!-- obsolete -->

app/views/reports/edit.html.erb
<%= form_for(@report, :html => { :class => 'mws-form' }) do |f| %>
	<div class="mws-panel grid_8">
		<div class="mws-panel-header">
			<span><%= Report.model_name.human %></span>
		</div>
		<div class="mws-panel-body no-padding">

			<div class="mws-form-inline">
				<%= render partial: 'shared/errors', locals: { object: @report } %>

				<div class="mws-form-row">
					<%= f.label :status, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.select :status, report_status_select_options(@report.status), {}, { :class => 'selectpicker' } %>
					</div>
				</div>
				
				<div class="mws-form-row">
					<%= f.label :inspection_object_nr, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.text_field :inspection_object_nr, :readonly => true %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :employee_id, t('.inspector'), :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.collection_select :employee_id, Employee.all, :id, :fullname, {}, { :readonly => true, :class => 'mws-select2 small' } %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :inspection_date, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.text_field :inspection_date, :readonly => true %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :scope_id, Scope.model_name.human, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.grouped_collection_select :scope_id, Program.all, :scopes, :name, :id, :name, {}, { :readonly => true, :class => 'mws-select2 small' } %>
					</div>
				</div>
				
				<div class="mws-form-row">
					<%= f.label :comments, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.text_area :comments, :class => 'large autosize' %>
					</div>
				</div>
								
				<div class="mws-button-row">
					<%= f.submit t('form.save'), :class => 'btn btn-danger' %>
				</div>
				
			</div>
		</div>
	</div>

	<div class="mws-panel grid_8 mws-collapsible">
		<div class="mws-panel-header">
			<span><%= ReportItem.model_name.human(count: 2) %></span>
		</div>
		<div class="mws-panel-body no-padding">
			<table class="mws-table">
				<tbody>
					<%= f.fields_for :report_items, @report.report_items.joins(:section).includes(:section).order("seq_nr") do |i| %>
						<tr>
							<td width="100px">
								<%= i.hidden_field :id %>
								<%= i.select :assessment, options_for_select(@assessment_options, i.object.assessment), {}, { 'data-style' => report_assessment_class(i.object.assessment), :class => 'selectpicker' }  %>
							</td>
							<td><%= i.object.section.nr %>
							</td>
							<td>
								<% if !i.object.section.title.blank? %>
									<strong><%= i.object.section.title %></strong>
									<% if !i.object.section.text.blank? %>
										<br/>
									<% end %>
								<% end %>
								<%= i.object.section.text.html_safe %>
								<div class="am-comments">
									<div class="mws-form-item"><%= i.text_area :comments, :class => "large autosize" %></div><br/>
								</div>
								<% if !i.object.section.instruction.blank? %>
									<div class="am-instruction"><div class="am-instruction-inner"><h3 class="am-instruction-title"><%= Section.human_attribute_name('instruction') %></h3><div class="am-instruction-content"><p><%= i.object.section.instruction.html_safe %></p></div></div></div>
								<% end %>
								<br/>
								<table id="attachment-table-<%= i.object.id%>" style="width: 100%">
									<tbody>
										<%= render :partial => 'report_item_attachments/attachment', :collection => i.object.attachments, :as => :attachment %>
									</tbody>
								</table>							
									
							</td>
							<td width="40px">
								<div class="btn-toolbar">
									<div class="btn-group">
										<div class="btn btn-small am-btn-comments"><i class='icon-edit'></i></div>
										<div class="btn btn-small am-btn-attachment" data-url="<%= report_item_report_item_attachments_path(i.object) %>" data-id="<%= i.object.id %>"><i class='icon-attachment'></i></div>
									<% if !i.object.section.instruction.blank? %>
										<div class="btn btn-small am-btn-instruction"><i class='icon-comment-2'></i></div>
									<% end %>
									</div>
								</div>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	
<% end %>
	
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Equipment.model_name.human(count: 2) %></span>
	</div>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
				<%= raw("<i class='icol-add'></i> "+t('form.add')) %>
				<span class="caret"></span>
  				</a>
  				<ul class="dropdown-menu">
				<% @report.employee.equipment.where("NOT EXISTS ( SELECT equipment_id FROM report_equipments WHERE report_id = :report_id AND equipment_id = equipment.id)", :report_id => @report.id).each do |equipment| %>
					<li><%= link_to "#{equipment.equipment_type.name}, #{equipment.equipment_type.model}", add_equipment_report_path(@report, :equipment_id => equipment.id), :method => :post %></li>
				<% end %>
  				</ul>
			</div>
		</div>
	</div>	
	<div class="mws-panel-body no-padding">
		<table class="mws-table">
			<thead>
				<tr>
					<th><%= EquipmentType.human_attribute_name('image') %></th>
					<th><%= EquipmentType.human_attribute_name('name') %></th>
					<th><%= EquipmentType.human_attribute_name('model') %></th>
					<th><%= Equipment.human_attribute_name('nr' ) %></th>
					<th><%= Equipment.human_attribute_name('serial_nr' )%></th>
					<th width="100px"></th>
				</tr>
			</thead>
			<tbody>
			<% @report.report_equipments.each do |report_equipment| %>
				<tr>
					<td align="center"><% if !report_equipment.equipment.equipment_type.image_url.nil? %><%= link_to image_tag(report_equipment.equipment.equipment_type.image_url(:thumb).to_s, :class => 'img-polaroid', :size => "100x60"), report_equipment.equipment.equipment_type %><%end %></td>
					<td><%= report_equipment.equipment.equipment_type.name %></td>
					<td><%= report_equipment.equipment.equipment_type.model %></td>
					<td><%= report_equipment.equipment.nr %></td>
					<td><%= report_equipment.equipment.serial_nr %></td>
					<td width="100px">
						<span class="btn-group">
							<%= link_to(raw("<i class='icon-trash'></i>"), report_equipment, method: :delete, data: { confirm: t('form.confirm_delete') }, :class => 'btn btn-small') %>
						</span>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

<div id="am-dialog-upload-attachments" style="padding: 0 0; display: none">
	<div id="uploader" data-url="bogus-url">
		<p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
        if( $.fn.dialog ) {
            $("#am-dialog-upload-attachments").dialog({
                autoOpen: false,
                title: "<%= t('.upload_attachments') %>",
                modal: true,
                width: "640",
                buttons: [{
                    text: "<%= t('form.cancel') %>",
                    click: function () {
                        $(this).dialog("close");
                    }
                }]
            });
            $(".am-btn-attachment").bind("click", function (event) {
			    $('#uploader').pluploadQueue().settings.url = $(this).data('url')
				var report_item_id = $(this).data('id')
				$('#uploader').pluploadQueue().bind('FileUploaded', function(up, file, info) {
					$("#attachment-table-"+report_item_id+" tbody").append(info['response']);
					$('.delete-attachment').bind('ajax:success', function() {
						$(this).closest('tr').remove();  
					});
					$.fn.prettyPhoto && $("a[rel^='prettyPhoto']").prettyPhoto({social_tools:false});
					$(".best_in_place").best_in_place();
				})
				
                $("#am-dialog-upload-attachments").dialog("option", {
                    modal: false
                }).dialog("open");
                event.preventDefault();
            });
		};
		
		$('.delete-attachment').bind('ajax:success', function() { 
    		$(this).closest('tr').remove();  
		});
		
		$.fn.prettyPhoto && $("a[rel^='prettyPhoto']").prettyPhoto({social_tools:false});
		
        if( $.fn.pluploadQueue ) {

			plupload.addI18n({
			   'Select files' : I18n.t('js.plupload.select_files'),
			   'Add files to the upload queue and click the start button.' : I18n.t('js.plupload.add_files_to_upload_queue'),
			   'Filename' : I18n.t('js.plupload.filename'),
			   'Status' : I18n.t('js.plupload.status'),
			   'Size' : I18n.t('js.plupload.size'),
			   'Add files' : I18n.t('js.plupload.add_files'),
			   'Stop current upload' : I18n.t('js.plupload.stop_upload'),
			   'Start uploading queue' : I18n.t('js.plupload.start_upload'),
			   'Uploaded %d/%d files': I18n.t('js.plupload.upload_files'),
			   'N/A' : I18n.t('js.plupload.not_available'),
			   'Drag files here.' : I18n.t('js.plupload.drag_files_here'),
			   'File extension error.': I18n.t('js.plupload.file_extension_error'),
			   'File size error.': I18n.t('js.plupload.file_size_error'),
			   'Init error.': I18n.t('js.plupload.init_error'),
			   'HTTP Error.': I18n.t('js.plupload.http_error'),
			   'Security error.': I18n.t('js.plupload.security_error'),
			   'Generic error.': I18n.t('js.plupload.generic_error'),
			   'IO error.': I18n.t('js.plupload.io_error')
			});

            $("#uploader").pluploadQueue({
                // General settings
                runtimes: 'html5, html4',
                url: '',
                max_file_size: '1000mb',
                max_file_count: 20, // user can add no more then 20 files at a time
                chunk_size: '1mb',
                unique_names: true,
                multiple_queues: true,
                multipart: true,
                multipart_params: {
         			"authenticity_token" : '<%= form_authenticity_token %>'
        		},

                // Resize images on clientside if we can
                resize: {
                    width: 320,
                    height: 240,
                    quality: 90
                },

                // Rename files by clicking on their titles
                rename: true,

                // Sort files
                sortable: true,

                // Specify what files to browse for
                filters: [{
                    title: "Afbeeldingen",
                    extensions: "jpg,gif,png,pdf,docx"
                },{
                    title: "Alle typen",
                    extensions: "*"
                }],

                init: {
                	FileUploaded: function(up, file, info) {

					}
            	}
            });

        }
		
	});
</script>

app/views/reports/index.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><i class="icon-table"></i> <%= Report.model_name.human(count: 2) %></span>
	</div>

	<% if policy(Report).new? %>
	<div class="mws-panel-toolbar">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to raw("<i class='icol-add'></i> "+t('form.add')), new_report_path, { :class => "btn" } %>
			</div>
		</div>
	</div>
	<% end %>

	<div class="mws-panel-body">
		<%= form_tag reports_path, :method => 'get' do %>
			<%= text_field_tag :id, params[:id], :placeholder => Report.human_attribute_name('id') %>
			<%= text_field_tag :object_nr, params[:object_nr], { :class => 'mws-select-ajax', :style => "width: 400px", :data  => { :source => inspection_objects_url(format: "json"), :placeholder => t('.all_objects') } } %>
			<%= select_tag :employee_id, options_from_collection_for_select(Employee.order("lastname"), "id", "fullname", params[:employee_id]), :include_blank => true, :class => "mws-select2", :style => "width: 200px", :data => { :placeholder => t('.all_inspectors') }  %>
			<%= select_tag :client_id, options_from_collection_for_select(Client.order("name"), "id", "name", params[:client_id]), :include_blank => true, :class => "mws-select2", :style => "width: 200px", :data => { :placeholder => t('.all_clients') }  %>
			<%= button_tag t('form.reset'), :name => nil, :type => "button", :class => 'btn clear-form'%>
			<%= submit_tag t('form.search'), :name => nil, :class => 'btn btn-inverse'%>
		<% end %>
	</div>

	<div class="mws-panel-body no-padding">
		<table class="mws-table mws-datatable" data-source="<%= reports_url(format: "json", id: params[:id], object_nr: params[:object_nr], employee_id: params[:employee_id], client_id: params[:client_id]) %>" data-sort-column="4" data-sort-direction="desc">
			<thead>
				<tr>
					<th style="width: 60px">ID</th>
					<th><%= Report.human_attribute_name('status') %></th>
					<th><%= InspectionObject.model_name.human %></th>
					<th><%= Client.model_name.human %></th>
					<th><%= Report.human_attribute_name('inspection_date') %></th>
					<th><%= Program.model_name.human %></th>
					<th><%= Scope.model_name.human %></th>
					<th><%= t('.inspector') %></th>
					<th class="no-sort" width="40px"></th>
					<th class="no-sort" width="150px"></th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>

app/views/reports/new.html.erb
<%= form_for(@report, :html => { :class => 'mws-form' }) do |f| %>
	<div class="mws-panel grid_8">
		<div class="mws-panel-header">
			<span><%= t('.new_report') %></span>
		</div>
		<div class="mws-panel-body no-padding">

			<div class="mws-form-inline">
				<%= render partial: 'shared/errors', locals: { object: @report } %>
				
				<div class="mws-form-row">
					<%= f.label :inspection_object_nr, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.text_field :inspection_object_nr, { :class => 'mws-select-ajax small', :data  => { :source => inspection_objects_url(format: "json"), :placeholder => t('.select_object') } } %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :employee_id, t('.inspector'), :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.collection_select :employee_id, Employee.order(:lastname), :id, :fullname, {:include_blank => true}, { :class => 'mws-select2 small' } %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :inspection_date, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.text_field :inspection_date, :class => 'mws-datepicker' %>
					</div>
				</div>
		
				<div class="mws-form-row">
					<%= f.label :scope_id, :class => 'mws-form-label' %>
					<div class="mws-form-item">
						<%= f.grouped_collection_select :scope_id, Program.all, :scopes, :name, :id, :name, {:include_blank => true}, { :class => 'mws-select2 small' } %>
					</div>
				</div>
		
				<div class="mws-button-row">
					<%= f.submit t('form.save'), :class => 'btn btn-danger' %>
				</div>
				
			</div>
		</div>
	</div>

<% end %>